scene_list = {
    'D1'  : ['knife', 'fork', 'plate'],
    'D2'  : ['knife', 'fork', 'plate', 'fruit'],
    'D3'  : ['knife', 'fork', 'plate', 'glass'],
    'D4'  : ['knife', 'fork', 'plate', 'glass', 'fruit'],
    'D5'  : ['knife', 'fork', 'plate', 'cup'],
    'D6'  : ['knife', 'fork', 'plate', 'cup', 'teapot'],
    'D7'  : ['knife', 'fork', 'plate', 'can_drink', 'cup'],
    'D8' : ['fork', 'knife', 'plate', 'small_bowl', 'glass'],
    'D9' : ['fork', 'fork', 'knife', 'spoon', 'plate', 'glass'],
    'D10' : ['fork', 'knife', 'plate', 'small_bowl', 'glass', 'fruit'],
    'D11' : ['fork', 'knife', 'plate', 'small_bowl', 'small_plate', 'glass', 'fruit'],
    'D12' : ['fork', 'fork', 'knife', 'spoon', 'small_bowl', 'small_plate', 'small_knife', 'glass', 'pitcher'],
    'D13' : ['fork', 'fork', 'knife', 'knife', 'plate', 'plate'],
    'D14' : ['fork', 'fork', 'knife', 'knife', 'plate', 'plate', 'glass', 'glass'],
    'D15' :  ['fork', 'fork', 'knife', 'knife', 'plate', 'plate', 'glass', 'glass', 'pitcher'],
    'D16' :  ['fork', 'fork', 'knife', 'knife', 'plate', 'plate', 'glass', 'glass', 'fruit'],
    "O1": ["book", "marker"],
    "O2": ["book", "marker", "cup"],
    "O3": ["book", "marker", "can_drink", "cup"],
    "O4": ["book", "marker", "can_drink", "cup", "stapler"],
    "O5": ["marker", "can_drink", "cup", "stapler", "glue"],
    "O6": ["marker", "can_drink", "cup", "stapler", "glue", "scissors"],
    "O7": ["can_drink", "can_drink", "cup", "stapler", "scissors"],
    "O8": ["marker", "can_drink", "can_drink", "cup", "stapler", "scissors"],
    "O9": ["book", "book", "marker"],
    "O10": ["book", "book", "marker", "can_drink", "cup"],
    "O11": ["book", "marker", "stapler", "scissors", "glue"],
    "O12": ["book", "marker", "stapler", "can_drink", "cup"],
    "O13": ["book", "marker", "stapler", "scissors", "glue", "cup"],
    "O14": ["book", "book", "marker", "stapler", "scissors", "glue", "cup"],
    "B1": ["soap", "soap_dish"],
    "B2": ["soap", "soap_dish", "toothpaste"],
    "B3": ["soap", "soap_dish", "cleanser"],
    "B4": ["soap", "soap_dish", "cleanser", "toothpaste"],
    "B5": ["soap", "soap_dish", "cleanser", "toothpaste", "lotion"],
    "B6": ["soap", "soap_dish", "cleanser", "toothpaste", "lotion", "shampoo"],
    "B7": ["soap", "soap_dish", "cleanser", "shampoo"],
    "B8": ["soap", "soap_dish", "shampoo", "toothpaste"],
    "C1": ["remote", "can_drink", "cup"],
    "C2": ["book", "remote", "can_drink", "cup"],
    "C3": ["book", "remote", "can_drink", "cup", "glass"],
    "C4": ["remote", "teapot", "cup"],
    "C5": ["remote", "teapot", "cup", "cup"],
    "C6": ["book", "remote", "teapot", "cup"],
    "C7": ["book", "remote", "teapot", "cup", "cup"],
    "C8": ["book", "remote", "can_drink", "cup", "bowl"],
    "C9": ["book", "book", "remote", "can_drink", "cup"],
    "C10": ["remote", "teapot", "cup", "cup", "bowl"],
    "C11": ["book", "book", "remote", "can_drink", "cup", "bowl"],
    "C12": ["remote", "can_drink", "cup", "teapot", "cup"],
    "C13": ["remote", "can_drink", "cup", "teapot", "glass"],
    "C14": ["remote", "can_drink", "cup", "teapot", "glass", "bowl"]
}

cat_to_name_train = {
	'book': ['pybullet/book_3', 'pybullet/book_2', 'pybullet/book_4', 'pybullet/book_1'],
	'bowl': ['pybullet/yellow_bowl', 'pybullet/doraemon_bowl', 'pybullet/green_bowl'],
	'can_drink': ['housecat/can-monster_blue', 'housecat/can-beer_delta', 'housecat/can-coke_small', 'housecat/can-redbull', 'housecat/can-hoegaarden'],
	'can_food': ['housecat/can-meatball', 'housecat/can-spam', 'housecat/can-concentrated_tall', 'ycb/010_potted_meat_can', 'housecat/can-small_tuna', 'housecat/can-sheba_cat', 'housecat/can-large_tuna', 'housecat/can-corn', 'ycb/005_tomato_soup_can', 'housecat/can-fricadelles', 'housecat/can-tuna_salad', 'housecat/can-corn_small', 'housecat/can-cheakpeas', 'housecat/can-corned_beef'],
	'cleanser': ['housecat/tube-kiwi', 'housecat/tube-perfax', 'housecat/tube-mdf_filler', 'housecat/tube-shoe_polish', 'housecat/tube-skincare_provencale', 'housecat/tube-skincare_hydralist', 'housecat/tube-wasabi', 'housecat/tube-wipp', 'housecat/tube-signal', 'housecat/tube-signal_pokemon', 'housecat/tube-shampoo_yellow'],
	'cup': ['housecat/cup-white_coffee_round_handle', 'housecat/cup-white_whisker', 'pybullet/mug', 'housecat/cup-plastic_green_flowers', 'housecat/cup-stanford', 'housecat/cup-white_hogermann', 'housecat/cup-mc_cafe', 'housecat/cup-new_york', 'housecat/cup-red_heart', 'housecat/cup-yellow_handle', 'housecat/cup-teal_pattern_ikea', 'housecat/cup-new_york_big', 'housecat/cup-grey_handle', 'housecat/cup-yellow_white_border', 'pybullet/blue_cup'],
	'fork': ['housecat/cutlery-fork_2_new', 'pybullet/fork', 'housecat/cutlery-fork_1', 'housecat/cutlery-fork_1_new'],
	'fruit': ['pybullet/plastic_pear', 'pybullet/plastic_peach', 'pybullet/plastic_plum', 'pybullet/plastic_apple', 'pybullet/plastic_lemon'],
	'glass': ['housecat/glass-new_6', 'housecat/glass-new_3', 'housecat/glass-new_13', 'housecat/glass-small_3', 'housecat/glass-new_4', 'housecat/glass-new_11', 'housecat/glass-small', 'housecat/glass-new_1', 'housecat/glass-new_5', 'housecat/glass-new_8', 'housecat/glass-new_12'],
	'glue': ['pybullet/glue_1', 'pybullet/glue_2'],
	'knife': ['housecat/cutlery-knife_1', 'pybullet/knife', 'housecat/cutlery-knife_1_new', 'housecat/cutlery-knife_3_new', 'housecat/cutlery-knife_2_new'],
	'lotion': ['housecat/bottle-today', 'housecat/bottle-shampoo_doux', 'housecat/bottle-cleansing_lotion_small', 'housecat/bottle-nivea'],
	'marker': ['pybullet/black_marker', 'pybullet/red_marker', 'pybullet/small_marker'],
	'pitcher': ['pybullet/pitcher'],
	'plate': ['pybullet/round_plate_3', 'pybullet/round_plate_2', 'pybullet/square_plate_1', 'pybullet/round_plate_1', 'pybullet/plate', 'pybullet/square_plate_2', 'pybullet/square_plate_3'],
	'scissors': ['ycb/037_scissors', 'pybullet/scissors'],
	'shampoo': ['housecat/bottle-baby_cleansing_water', 'housecat/bottle-avene_skincare'],
	'soap': ['pybullet/soap'],
	'soap_dish': ['pybullet/soap_dish'],
	'spoon': ['housecat/cutlery-spoon_1_new', 'housecat/cutlery-spoon_2_new', 'housecat/cutlery-spoon_2', 'housecat/cutlery-spoon_1', 'pybullet/spoon', 'housecat/cutlery-spoon_3_new', 'housecat/cutlery-spoon_5_new'],
	'stapler': ['pybullet/stapler_2', 'pybullet/stapler_1'],
	'teapot': ['housecat/teapot-white_small', 'housecat/teapot-new_chinese', 'housecat/teapot-green_grass', 'housecat/teapot-white_royal_norfolk', 'housecat/teapot-white_blue_cone_top', 'housecat/teapot-white_rectangle_sprout', 'housecat/teapot-white_was_brand', 'housecat/teapot-wooden_color', 'housecat/teapot-white_rectangle', 'housecat/teapot-pale_pink', 'housecat/teapot-white_black_line', 'housecat/teapot-white_spherical', 'housecat/teapot-white_malacasa', 'housecat/teapot-white_floral'],
	'timer': ['ycb/076_timer'],
	'toothpaste': ['housecat/tube-toothpaste_signal_kids_bio', 'pybullet/toothpaste_1'],
}

cat_to_name_test = {
	'book': ['pybullet/book_5'],
	'bowl': ['pybullet/bowl'],
	'can_drink': ['housecat/can-fanta', 'housecat/can-monster'],
	'can_food': ['housecat/can-target_beef', 'housecat/can-olive_anchois', 'ycb/002_master_chef_can', 'housecat/can-kidney_beans'],
	'cleanser': ['housecat/tube-creme_yellow', 'housecat/tube-baby_nivea_comfort', 'housecat/tube-hansaplast_gel', 'housecat/tube-baby_nivea_spf'],
	'cup': ['pybullet/orange_cup', 'pybullet/yellow_cup', 'housecat/cup-green_handle', 'housecat/cup-green_actys', 'pybullet/green_cup', 'housecat/cup-red'],
	'fork': ['housecat/cutlery-fork_3_new'],
	'fruit': ['pybullet/plastic_orange', 'pybullet/plastic_strawberry'],
	'glass': ['housecat/glass-new_7', 'housecat/glass-new_9', 'housecat/glass-small_4', 'housecat/glass-new_2', 'housecat/glass-new_10'],
	'glue': [],
	'knife': ['housecat/cutlery-knife_2'],
	'lotion': ['housecat/tube-bb_cream', 'pybullet/conditioner', 'pybullet/shampoo'],
	'marker': ['pybullet/large_marker', 'pybullet/blue_marker'],
	'plate': ['pybullet/round_plate_4', 'pybullet/blue_plate', 'pybullet/square_plate_4', 'pybullet/grey_plate'],
	'scissors': ['ycb/037_scissors', 'pybullet/scissors'],
	'shampoo': ['housecat/bottle-alcool_hands'],
	'soap': [],
	'soap_dish': [],
	'spoon': ['housecat/cutlery-spoon_4_new', 'housecat/cutlery-spoon_6_new'],
	'stapler': [],
	'teapot': ['housecat/teapot-ambition_brand', 'housecat/teapot-brown_chinese', 'housecat/teapot-brown_small', 'housecat/teapot-blue_floral', 'housecat/teapot-big_white_floral'],
	'timer': [],
	'toothpaste': [],
}